"""Validate and write decision_response.json for the Adaptive Futures Agent.

Version 1 goals:
- Keep a stable, practical JSON contract for NinjaTrader 8 integration
- Fail safely when payloads are malformed or incomplete
- Write output atomically to reduce partial-read risk
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Required top-level keys for Version 1 decision responses.
REQUIRED_FIELDS: tuple[str, ...] = (
    "timestamp_et",
    "source_market_timestamp_et",
    "instrument",
    "decision_status",
    "regime",
    "event_state",
    "specialist",
    "policy",
    "risk_overlay",
    "execution_plan",
    "integration_meta",
)

# Helpful defaults for keys that are usually object-shaped in this integration contract.
OBJECT_DEFAULTS: dict[str, dict[str, Any]] = {
    "regime": {},
    "event_state": {},
    "specialist": {},
    "policy": {},
    "risk_overlay": {},
    "execution_plan": {},
    "integration_meta": {},
}


def configure_default_logging(level: int = logging.INFO) -> None:
    """Set up basic logging if the host app has not configured logging yet."""
    root_logger = logging.getLogger()
    if not root_logger.handlers:
        logging.basicConfig(
            level=level,
            format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
        )


def write_decision_response(
    decision: dict[str, Any],
    file_path: str | Path = "decision_response.json",
) -> bool:
    """Validate and safely write a decision response JSON file.

    Args:
        decision: Final decision dictionary generated by Python logic.
        file_path: Output path for decision_response.json.

    Returns:
        True if write succeeded, False otherwise.
    """
    if not isinstance(decision, dict):
        logger.error("Decision write failed: payload must be a dict/object.")
        return False

    prepared_decision = _prepare_decision(decision)
    if prepared_decision is None:
        return False

    path = Path(file_path)
    return _atomic_write_json(path, prepared_decision)


def _prepare_decision(decision: dict[str, Any]) -> dict[str, Any] | None:
    """Normalize and validate payload shape for Version 1 contract."""
    normalized = dict(
        decision)  # shallow copy so caller data is not modified in-place

    # Fill object-like keys with empty dict defaults if omitted.
    for field, default_value in OBJECT_DEFAULTS.items():
        normalized.setdefault(field, default_value)

    if not _validate_decision(normalized):
        return None

    # Keep output key order stable for readability/logging/debugging.
    ordered = {field: normalized[field] for field in REQUIRED_FIELDS}

    # Preserve any additional fields (future-friendly, while keeping required keys first).
    for key, value in normalized.items():
        if key not in ordered:
            ordered[key] = value

    return ordered


def _validate_decision(decision: dict[str, Any]) -> bool:
    """Run basic, practical schema checks for Version 1."""
    missing_fields = [
        field for field in REQUIRED_FIELDS if field not in decision]
    if missing_fields:
        logger.error(
            "Decision validation failed: missing required fields: %s",
            ", ".join(missing_fields),
        )
        return False

    for field in ("timestamp_et", "source_market_timestamp_et", "instrument", "decision_status"):
        value = decision.get(field)
        if not isinstance(value, str) or not value.strip():
            logger.error(
                "Decision validation failed: field '%s' must be a non-empty string.", field)
            return False

    for field in OBJECT_DEFAULTS:
        value = decision.get(field)
        if not isinstance(value, dict):
            logger.error(
                "Decision validation failed: field '%s' must be an object/dict.", field)
            return False

    return True


def _atomic_write_json(path: Path, payload: dict[str, Any]) -> bool:
    """Write JSON atomically via temporary file + replace.

    On most modern filesystems, Path.replace() is atomic when source and target are
    on the same filesystem, which is why the temp file is created in the target folder.
    """
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        logger.error(
            "Decision write failed: could not create parent directory for %s: %s", path, exc)
        return False

    temp_path = path.with_name(f".{path.name}.tmp")

    try:
        with temp_path.open("w", encoding="utf-8") as temp_file:
            json.dump(payload, temp_file, indent=2, ensure_ascii=False)
            temp_file.write("\n")
        temp_path.replace(path)
        logger.info("Decision response written: %s", path)
        return True
    except OSError as exc:
        logger.error("Decision write failed for %s: %s", path, exc)
        _cleanup_temp_file(temp_path)
        return False
    except TypeError as exc:
        # Raised if payload contains non-JSON-serializable values.
        logger.error(
            "Decision write failed: payload is not JSON serializable: %s", exc)
        _cleanup_temp_file(temp_path)
        return False


def _cleanup_temp_file(temp_path: Path) -> None:
    """Best-effort cleanup if a temp write failed mid-way."""
    try:
        if temp_path.exists():
            temp_path.unlink()
    except OSError as exc:
        logger.warning(
            "Could not remove temp decision file %s: %s", temp_path, exc)


__all__ = [
    "REQUIRED_FIELDS",
    "configure_default_logging",
    "write_decision_response",
]
